version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: 'Mk3OEYBSD3t9SlvVvQ4Z8Q'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "python3", "-c", "import socket; s = socket.socket(); s.connect(('localhost', 9092))"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    image: timescale/timescaledb:latest-pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kickboxing12#
      POSTGRES_DB: football_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: football-spark-master
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      PYTHONPATH: /opt/src
    volumes:
      - ./src:/opt/src
      - ./data:/opt/data

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: football-spark-worker
    depends_on:
      - spark-master
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
    environment:
      PYTHONPATH: /opt/src
    volumes:
      - ./src:/opt/src
      - ./data:/opt/data

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    ports:
      - "8081:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:Kickboxing12#@postgres:5432/football_db
      - AIRFLOW__WEBSERVER__WORKERS=2
    command: standalone
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  pg_data: