FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/football_etl ./football_etl

CMD ["python", "-m", "football_etl.kafka_producer"]
